Repository inbo/aspbo, pull requests merged in 2025-01, with the labels that each got.

#305 [AUTO] get muskrat data
  data/interim/muskrat_missing_provinces_final.csv
  data/output/UAT_direct/Ondatra_zibethicus.csv
Labels: automated workflow

#309 [AUTO] download griis checklist
  .github/workflows/get_griis_checklist.yaml
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#311 [AUTO] get muskrat data
  data/interim/muskrat_missing_provinces_final.csv
  data/output/UAT_direct/Ondatra_zibethicus.csv
Labels: automated workflow

#294 18 disable no filter query
  .github/workflows/get_occ_cube.yaml
  data/interim/cube_queries/griis_belgium_genus_query.txt
  data/interim/cube_queries/griis_belgium_no_filter_query.txt
  data/interim/cube_queries/griis_belgium_species_query.txt
  data/interim/cube_queries/griis_belgium_subspecies_form_variety_query.txt
  src/get_cubes/build_queries.Rmd
  src/get_cubes/compile_cubes.Rmd
Labels: bug, automated workflow

#314 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/interim/taxa_last_observed_in_BE_before_1950.tsv
Labels: automated workflow

#317 253 update translations for alien species portal v110
  data/output/UAT_direct/translations.csv
  data/output/UAT_direct/translations_simple.csv
  src/translation_editor.R
Labels: documentation

#320 [AUTO] get muskrat data
  data/interim/muskrat_missing_provinces_final.csv
  data/output/UAT_direct/Ondatra_zibethicus.csv
Labels: automated workflow

#323 [AUTO] get muskrat data
  data/interim/muskrat_missing_provinces_final.csv
  data/output/UAT_direct/Ondatra_zibethicus.csv
Labels: automated workflow

#327 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/interim/taxa_last_observed_in_BE_before_1950.tsv
Labels: automated workflow

#332 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/interim/taxa_last_observed_in_BE_before_1950.tsv
Labels: automated workflow
