Repository inbo/aspbo, pull requests merged in 2025-03, with the labels that each got.

#350 [AUTO] download griis checklist
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#352 [AUTO] get muskrat data
  data/interim/muskrat_missing_provinces_final.csv
  data/output/UAT_direct/Ondatra_zibethicus.csv
Labels: automated workflow

#355 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/interim/taxa_last_observed_in_BE_before_1950.tsv
Labels: automated workflow

#343 Delete Muntiacus_reveesi_culling.csv
  data/output/UAT_direct/Muntiacus_reveesi_culling.csv
Labels: bug, enhancement

#362 [AUTO] download griis checklist
  .github/workflows/get_griis_checklist.yaml
  data/input/belgium_class_base.txt
  data/input/griis_belgium_family_base.txt
  data/input/griis_belgium_genus_base.txt
  data/input/griis_belgium_species_base.txt
  data/input/griis_belgium_subspecies_form_variety_base.txt
  data/output/UAT_processing/data_input_checklist_indicators.tsv
  src/GRIIS_processing.Rmd
  src/cube_preprocessing.Rmd
  src/download_griis_checklist.R
  src/install_packages_get_griis.R
Labels: automated workflow

#365 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/output/UAT_processing/data_input_checklist_indicators.tsv
  src/cube_preprocessing.Rmd
Labels: automated workflow

#366 [AUTO] update cube_preprocessing
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#367 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
Labels: automated workflow

#354 add vernacular_name to translate_simple
  data/output/UAT_direct/translations_simple.csv
Labels: enhancement

#371 [AUTO] get muskrat data
  data/interim/muskrat_missing_provinces_final.csv
  data/output/UAT_direct/Ondatra_zibethicus.csv
Labels: automated workflow
