Repository inbo/aspbo, pull requests merged in 2025-04, with the labels that each got.

#370 [AUTO] update cube_preprocessing
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#375 [AUTO] download griis checklist
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#303 295 create faq page
  HTML_pages/HTML/FAQ_en.html
  HTML_pages/HTML/FAQ_fr.html
  HTML_pages/HTML/FAQ_nl.html
  HTML_pages/Rmd_files/faq.Rmd
Labels: documentation, enhancement

#379 [AUTO] update cube_preprocessing
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#380 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#381 [AUTO] get muskrat data
  data/interim/muskrat_missing_provinces_final.csv
  data/output/UAT_direct/Ondatra_zibethicus.csv
Labels: automated workflow

#376 add concurrency to upload_files_processing
  .github/workflows/upload_files_processing.yaml
Labels: enhancement, automated workflow

#377 add concurrency to upload_files_direct
  .github/workflows/upload_files_direct.yaml
Labels: enhancement, automated workflow

#382 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#383 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/output/UAT_processing/data_input_checklist_indicators.tsv
Labels: automated workflow

#394 [AUTO] update cube_preprocessing
  data/interim/keys_missing_name.csv
  data/interim/keys_missing_taxonkey.csv
  data/interim/keys_old.csv
  data/interim/taxa_last_observed_in_BE_before_1950.tsv
  data/output/UAT_direct/keys.csv
  data/output/UAT_processing/data_input_checklist_indicators.tsv
  src/cube_preprocessing.Rmd
Labels: automated workflow

#391 390 translation tweaks v120
  data/output/UAT_direct/translations.csv
  data/output/UAT_direct/translations_simple.csv
Labels: enhancement

#397 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/interim/keys_old.csv
  data/output/UAT_direct/keys.csv
  data/output/UAT_processing/data_input_checklist_indicators.tsv
  src/cube_preprocessing.Rmd
Labels: automated workflow

#398 fix #396
  src/tests/test_regionIDs.R
Labels: bug, automated workflow

#399 [AUTO] update cube_preprocessing
  data/interim/alien_taxa_without_occs.tsv
  data/interim/keys_missing_taxonkey.csv
  data/interim/keys_old.csv
  data/output/UAT_direct/keys.csv
Labels: automated workflow
